name: homelab

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: ./backend
