// <auto-generated />
using System;
using Homelab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Homelab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729045501_AddFinanceBaseTables")]
    partial class AddFinanceBaseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Homelab.Data.Entities.FinanceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumberLastFour")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("account_number_last_four");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.HasKey("Id")
                        .HasName("pk_finance_accounts");

                    b.HasIndex("Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_finance_accounts_provider");

                    b.ToTable("finance_accounts", (string)null);
                });

            modelBuilder.Entity("Homelab.Data.Entities.FinanceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.HasKey("Id")
                        .HasName("pk_finance_transactions");

                    b.HasIndex("FinanceAccountId")
                        .HasDatabaseName("ix_finance_transactions_finance_account_id");

                    b.ToTable("finance_transactions", (string)null);
                });

            modelBuilder.Entity("Homelab.Data.Entities.FinanceTransaction", b =>
                {
                    b.HasOne("Homelab.Data.Entities.FinanceAccount", "FinanceAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_finance_transactions_finance_accounts_finance_account_id");

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Homelab.Data.Entities.FinanceAccount", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
